set(_MINECRAFT_CLIENT_3DS_COMMON
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_AUDIO}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_NETWORK}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_COMPONENTS}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_CONTROLS}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_DEBUG}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_FRONTEND_MENU_SCREENS}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_HELP__OPTIONS}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_INGAME_MENU_SCREENS}
	${_MINECRAFT_CLIENT_WINDOWS_COMMON_UI_SCENES_INGAME_MENU_SCREENS_CONTAINERS}
	${_MINECRAFT_CLIENT_WINDOWS_NET_MINECRAFT_STATS}
)
source_group("3DS/Common" FILES ${_MINECRAFT_CLIENT_3DS_COMMON})

set(_MINECRAFT_CLIENT_3DS_FILES
	"${CMAKE_CURRENT_SOURCE_DIR}/3DS/3DS_App.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/3DS/3DS_UIController.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/3DS/3DS_RuntimeStubs.cpp"
	"${CMAKE_CURRENT_SOURCE_DIR}/PS3/PS3Extras/ShutdownManager.cpp"
	"${CMAKE_CURRENT_SOURCE_DIR}/PS3/PS3Extras/ShutdownManager.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/3DS/4JLibs/inc/4J_Input.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/3DS/4JLibs/inc/4J_Profile.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/3DS/4JLibs/inc/4J_Render.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/3DS/4JLibs/inc/4J_Storage.h"
)
source_group("3DS" FILES ${_MINECRAFT_CLIENT_3DS_FILES})

set(MINECRAFT_CLIENT_3DS
	${_MINECRAFT_CLIENT_3DS_COMMON}
	${_MINECRAFT_CLIENT_3DS_FILES}
)
